# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BLDC_booster.ui'
#
# Created: Tue Oct 16 13:56:17 2012
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(633, 602)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Serial Port", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.comPort = QtGui.QLineEdit(self.groupBox)
        self.comPort.setText(QtGui.QApplication.translate("MainWindow", "COM42", None, QtGui.QApplication.UnicodeUTF8))
        self.comPort.setObjectName(_fromUtf8("comPort"))
        self.horizontalLayout_2.addWidget(self.comPort)
        self.connectBtn = QtGui.QPushButton(self.groupBox)
        self.connectBtn.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.connectBtn.setObjectName(_fromUtf8("connectBtn"))
        self.horizontalLayout_2.addWidget(self.connectBtn)
        self.disconnectBtn = QtGui.QPushButton(self.groupBox)
        self.disconnectBtn.setText(QtGui.QApplication.translate("MainWindow", "Disconnect", None, QtGui.QApplication.UnicodeUTF8))
        self.disconnectBtn.setObjectName(_fromUtf8("disconnectBtn"))
        self.horizontalLayout_2.addWidget(self.disconnectBtn)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.modeTab = QtGui.QTabWidget(self.centralwidget)
        self.modeTab.setMaximumSize(QtCore.QSize(16777215, 100))
        self.modeTab.setStyleSheet(_fromUtf8("background-color: rgb(238, 238, 238);"))
        self.modeTab.setTabPosition(QtGui.QTabWidget.North)
        self.modeTab.setObjectName(_fromUtf8("modeTab"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.dutyCycleGrp = QtGui.QGroupBox(self.tab)
        self.dutyCycleGrp.setTitle(QtGui.QApplication.translate("MainWindow", "Duty Cycle", None, QtGui.QApplication.UnicodeUTF8))
        self.dutyCycleGrp.setObjectName(_fromUtf8("dutyCycleGrp"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.dutyCycleGrp)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.dutyCycle = QtGui.QSpinBox(self.dutyCycleGrp)
        self.dutyCycle.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dutyCycle.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.dutyCycle.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.dutyCycle.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.dutyCycle.setMinimum(25)
        self.dutyCycle.setSingleStep(1)
        self.dutyCycle.setProperty("value", 50)
        self.dutyCycle.setObjectName(_fromUtf8("dutyCycle"))
        self.horizontalLayout_3.addWidget(self.dutyCycle)
        self.dutySlider = QtGui.QSlider(self.dutyCycleGrp)
        self.dutySlider.setMinimum(25)
        self.dutySlider.setProperty("value", 50)
        self.dutySlider.setOrientation(QtCore.Qt.Horizontal)
        self.dutySlider.setObjectName(_fromUtf8("dutySlider"))
        self.horizontalLayout_3.addWidget(self.dutySlider)
        self.gridLayout.addWidget(self.dutyCycleGrp, 0, 2, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Flux Threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.fluxThreshold = QtGui.QSpinBox(self.groupBox_2)
        self.fluxThreshold.setMinimumSize(QtCore.QSize(60, 0))
        self.fluxThreshold.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.fluxThreshold.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.fluxThreshold.setMaximum(3000)
        self.fluxThreshold.setSingleStep(25)
        self.fluxThreshold.setProperty("value", 900)
        self.fluxThreshold.setObjectName(_fromUtf8("fluxThreshold"))
        self.horizontalLayout_4.addWidget(self.fluxThreshold)
        self.fluxSlider = QtGui.QSlider(self.groupBox_2)
        self.fluxSlider.setMaximum(3000)
        self.fluxSlider.setProperty("value", 600)
        self.fluxSlider.setOrientation(QtCore.Qt.Horizontal)
        self.fluxSlider.setObjectName(_fromUtf8("fluxSlider"))
        self.horizontalLayout_4.addWidget(self.fluxSlider)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.enableChk = QtGui.QCheckBox(self.tab)
        self.enableChk.setText(QtGui.QApplication.translate("MainWindow", "Enable", None, QtGui.QApplication.UnicodeUTF8))
        self.enableChk.setObjectName(_fromUtf8("enableChk"))
        self.gridLayout.addWidget(self.enableChk, 0, 0, 1, 1)
        self.modeTab.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.modeTab.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.modeTab)
        self.debugGrp = QtGui.QGroupBox(self.centralwidget)
        self.debugGrp.setTitle(QtGui.QApplication.translate("MainWindow", "Debug Data", None, QtGui.QApplication.UnicodeUTF8))
        self.debugGrp.setObjectName(_fromUtf8("debugGrp"))
        self.verticalLayout = QtGui.QVBoxLayout(self.debugGrp)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.plotSelect = QtGui.QComboBox(self.debugGrp)
        self.plotSelect.setMinimumSize(QtCore.QSize(350, 0))
        self.plotSelect.setMaximumSize(QtCore.QSize(600, 16777215))
        self.plotSelect.setObjectName(_fromUtf8("plotSelect"))
        self.plotSelect.addItem(_fromUtf8(""))
        self.plotSelect.setItemText(0, QtGui.QApplication.translate("MainWindow", "VPWR", None, QtGui.QApplication.UnicodeUTF8))
        self.plotSelect.addItem(_fromUtf8(""))
        self.plotSelect.setItemText(1, QtGui.QApplication.translate("MainWindow", "BEMF", None, QtGui.QApplication.UnicodeUTF8))
        self.plotSelect.addItem(_fromUtf8(""))
        self.plotSelect.setItemText(2, QtGui.QApplication.translate("MainWindow", "BEMF + VPWR (interlaced)", None, QtGui.QApplication.UnicodeUTF8))
        self.plotSelect.addItem(_fromUtf8(""))
        self.plotSelect.setItemText(3, QtGui.QApplication.translate("MainWindow", "Filtered BEMF", None, QtGui.QApplication.UnicodeUTF8))
        self.plotSelect.addItem(_fromUtf8(""))
        self.plotSelect.setItemText(4, QtGui.QApplication.translate("MainWindow", "Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.plotSelect.addItem(_fromUtf8(""))
        self.plotSelect.setItemText(5, QtGui.QApplication.translate("MainWindow", "Integral", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout.addWidget(self.plotSelect)
        self.captureBtn = QtGui.QPushButton(self.debugGrp)
        self.captureBtn.setText(QtGui.QApplication.translate("MainWindow", "Capture", None, QtGui.QApplication.UnicodeUTF8))
        self.captureBtn.setObjectName(_fromUtf8("captureBtn"))
        self.horizontalLayout.addWidget(self.captureBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.plotWidget = MatplotlibWidget(self.debugGrp)
        self.plotWidget.setObjectName(_fromUtf8("plotWidget"))
        self.verticalLayout.addWidget(self.plotWidget)
        self.verticalLayout_2.addWidget(self.debugGrp)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 633, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.modeTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.modeTab.setTabText(self.modeTab.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Duty Cycle", None, QtGui.QApplication.UnicodeUTF8))
        self.modeTab.setTabText(self.modeTab.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Speed", None, QtGui.QApplication.UnicodeUTF8))

from matplotlibwidget import MatplotlibWidget
